# Generated by Django 5.0.2 on 2024-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=40)),
                ("about", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Non IT", "Non IT"),
                            ("Auto mobile", "auto mobile"),
                        ],
                        max_length=50,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
