# Generated by Django 5.0.2 on 2024-09-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("about", models.TextField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("manager", "manager"),
                            ("softwere developer", "softwere developer"),
                            ("HR", "HR"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "About_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
